/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package my.aircompany;

/**
 *
 * @author A00037189
 */
import java.awt.*;
import java.awt.event.*;
import java.io.File;
import java.io.IOException;
import java.sql.*;
import javax.swing.*;
import java.net.MalformedURLException;
import java.net.URL;
import javax.net.ssl.HttpsURLConnection;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;

public class Students extends javax.swing.JFrame {
    
    private String CustName;
    
    private String CustAcc;
    
    
    private String FlightDur;
    private String LocationId;
    private String Fee;
    private String FlightDate;
    private String TutorId;
    private String AirCraftId;
    
    private String sStuId="";
    private String  First="";
    private String  Sname="";
    private String sAddress="";
    private String sPhoneNo="";
    private String sEmail="";
    
    Connection con;
    Statement stmt;
    ResultSet rs;
    
    int count;
    int current;

    /**
     * Creates new form
     */
    public Students() {
        initComponents();
        con=null;
        stmt=null;
        rs=null;
        count=0;
        int current;
        CustName="";
       sStuId="";
       First="";
       Sname="";
       sAddress="";
       sPhoneNo="";
       sEmail="";
       
      
        
       
        
        FlightDur="";
        LocationId="";
        Fee="";
        FlightDate="";
        TutorId="";
        AirCraftId="";
        
       

        	dbConn();		// method to connect to database using odbc-jdbc
        	initDB();		// method to initialise gui with database info
   
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        F_Date = new javax.swing.JTextField();
        cName = new javax.swing.JTextField();
        Name = new javax.swing.JLabel();
        Account = new javax.swing.JLabel();
        AccType = new javax.swing.JLabel();
        aNum = new javax.swing.JTextField();
        Balance = new javax.swing.JLabel();
        BankLogo = new javax.swing.JLabel();
        Open = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        Previous = new javax.swing.JButton();
        Next = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        AccType1 = new javax.swing.JLabel();
        cFee = new javax.swing.JTextField();
        cLocation = new javax.swing.JTextField();
        PhoneNr1 = new javax.swing.JLabel();
        cFlightDur = new javax.swing.JTextField();
        cTutor = new javax.swing.JTextField();
        Account1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        File = new javax.swing.JMenu();
        ClearDetails = new javax.swing.JMenuItem();
        ExitScreen = new javax.swing.JMenuItem();
        About = new javax.swing.JMenu();
        Manual = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(java.awt.Color.white);

        F_Date.setText("jTextField1");
        F_Date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F_DateActionPerformed(evt);
            }
        });

        cName.setText("jTextField1");
        cName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cNameActionPerformed(evt);
            }
        });

        Name.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        Name.setText("Student Id");
        Name.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Account.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        Account.setText("Firstname");
        Account.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        AccType.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        AccType.setText("Email");
        AccType.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        aNum.setText("jTextField1");

        Balance.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        Balance.setText("Surname");
        Balance.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        BankLogo.setFont(new java.awt.Font("Calibri", 3, 24)); // NOI18N
        BankLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bankofirelandbk/KennyAir_Logo.PNG"))); // NOI18N
        BankLogo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BankLogo.setPreferredSize(new java.awt.Dimension(468, 115));

        Open.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        Open.setText("Book New Flight");
        Open.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenActionPerformed(evt);
            }
        });

        Exit.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        Previous.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        Previous.setText("Previous Record");
        Previous.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Previous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreviousActionPerformed(evt);
            }
        });

        Next.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        Next.setText("Next Record");
        Next.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextActionPerformed(evt);
            }
        });

        Clear.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        Clear.setText("Clear");
        Clear.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });

        AccType1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        AccType1.setText("Address");
        AccType1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        cFee.setText("jTextField1");
        cFee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cFeeActionPerformed(evt);
            }
        });

        cLocation.setText("jTextField2");

        PhoneNr1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        PhoneNr1.setText("Phone");
        PhoneNr1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        cFlightDur.setText("jTextField1");

        cTutor.setText("jTextField1");

        Account1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        Account1.setText("Tutor_Id");
        Account1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jButton1.setText("Back to Main");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jButton2.setText("Delete Student");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(AccType, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                                .addComponent(PhoneNr1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                                .addComponent(AccType1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                                .addComponent(Balance, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(Account1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(cFee, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                                                .addComponent(cFlightDur, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(cLocation))
                                            .addComponent(cTutor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(F_Date, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(Account, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(71, 71, 71)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cName, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(aNum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(171, 171, 171)
                                .addComponent(BankLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 169, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Previous, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Next, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Open, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(BankLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Account, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Balance)
                    .addComponent(F_Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cFlightDur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AccType))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cFee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AccType1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PhoneNr1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cTutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Account1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Open, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Next, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Previous, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        File.setText("File");

        ClearDetails.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK));
        ClearDetails.setText("Clear Details");
        ClearDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearDetailsActionPerformed(evt);
            }
        });
        File.add(ClearDetails);

        ExitScreen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_MASK));
        ExitScreen.setText("Exit");
        ExitScreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitScreenActionPerformed(evt);
            }
        });
        File.add(ExitScreen);

        jMenuBar1.add(File);

        About.setText("About");

        Manual.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        Manual.setText("User Manual");
        Manual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManualActionPerformed(evt);
            }
        });
        About.add(Manual);

        jMenuBar1.add(About);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void dbConn()
    {
	try	
	{		// load the jdbc-odbc bridge driver manager
		//Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
		
			// driver to use with named database
		
            String url = "jdbc:ucanaccess://c:/KennyAir/KennyAir.mdb";
  	
			// connection represents a session with a specific database
		con = DriverManager.getConnection(url);

			// stmt used for executing sql statements and obtaining results
		stmt = con.createStatement();

		rs = stmt.executeQuery("SELECT * FROM Students");

		while(rs.next())	// count number of rows in table
			count++;
		rs.close();
                System.out.println("Helloooooooo");
	}
	catch(Exception e) { System.out.println("Error in start up......");}
    }
private void initDB()
    {System.out.println("Helloooo");
	try		// display database info in gui
	{
		rs = stmt.executeQuery("SELECT * FROM Students");
		rs.next();   

		
   		sStuId = rs.getString("Student_Id");
		First = rs.getString("FirstName");
                Sname = rs.getString("SurName");
                sAddress = rs.getString("Address");
                sPhoneNo = rs.getString("Phone_No");
                sEmail = rs.getString("Email");
                TutorId = rs.getString("Tutor_Id");
                
                
		cName.setText(" " +sStuId);
		aNum.setText(" " +First);
		F_Date.setText(" " +Sname);
                cFee.setText(" "+ sAddress);
                cLocation.setText(" "+sPhoneNo);
                cFlightDur.setText(" "+sEmail);
                cTutor.setText(" "+TutorId);
                
                
                
		current = 1;
		rs.close();
                
            
                
	}
	catch(Exception e) {System.out.println("Error in initialising DB info to GUI");}
    }

    public void moveToRow(int index)
    {
	try
	{
		rs = stmt.executeQuery("SELECT * FROM Students");
		
		for(int i = 0; i < index; i++)
			rs.next();  	// move to specific row in table (at index)

		
                
                sStuId = rs.getString("Student_Id");
		First = rs.getString("FirstName");
                Sname = rs.getString("SurName");
                sAddress = rs.getString("Address");
                sPhoneNo = rs.getString("Phone_No");
                sEmail = rs.getString("Email");
                TutorId = rs.getString("Tutor_Id");
                
                cName.setText(" " +sStuId);
		aNum.setText(" " +First);
		F_Date.setText(" " +Sname);
                cFee.setText(" "+ sAddress);
                cLocation.setText(" "+sPhoneNo);
                cFlightDur.setText(" "+sEmail);
                cTutor.setText(" "+TutorId);

		
                
		current = index;
            
		rs.close();
	}
	catch(Exception e) {System.out.println("Error in moving to row at index specified");}
    }

    public void findCust(String nameToFind)
    {
	int foundCust = 0;
	boolean found = false;
			
	try		// get name to search database for, use .equals() to match names
	{
		System.out.println("Finding: " +nameToFind);
		rs = stmt.executeQuery("SELECT * FROM Students");

		while(rs.next() && found == false)
		{
			foundCust++;
			String CustName = rs.getString("CustName");			
			CustName.trim();	
						
			if(CustName.equals(nameToFind))
				found = true;
		}
		rs.close();
	}
	catch(Exception e) {System.out.println("Error in finding Customer in database");}

	if(found == true)
		moveToRow(foundCust);
	else
		cName.setText("Not Found");	
    }

            
    public void actionPerformed(ActionEvent event)
    {
	Object target = event.getSource();

	
    }
    
    
    
    
    
    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
          JOptionPane.showMessageDialog(Students.this,
    "You are about to exit the system",
    "System Exit", JOptionPane.PLAIN_MESSAGE);
        System.exit(0);
       // TODO add your handling code here:
    }//GEN-LAST:event_ExitActionPerformed

    private void cNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cNameActionPerformed
            // TODO add your handling code here:
    }//GEN-LAST:event_cNameActionPerformed

    private void NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextActionPerformed
            if(current != count)
			moveToRow(current+1);        
// TODO add your handling code here:
    }//GEN-LAST:event_NextActionPerformed

    //Book New Flight
    private void OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenActionPerformed
try
		{
              	
			String Acc = cName.getText();
			String Air_Id =  aNum.getText();
                        String Tutr_Id =  cTutor.getText();
                        String Fl_Date =  F_Date.getText();
                        String F_Dur =  cFlightDur.getText();
                        String FlightFee =  cFee.getText();
                        String Loc_Id =  cLocation.getText();
                 
			String newAcc = "INSERT INTO Students(Student_Id, FirstName, SurName, Address, Phone_Dur, Email, Tutor_Id)VALUES('"+Acc+"','"+Air_Id+"','"+Tutr_Id+"','"+Fl_Date+"','"+F_Dur+"','"+FlightFee+"','"+Loc_Id+"')";
			stmt.executeUpdate(newAcc);

			System.out.println(cName +" stored in database");
		}
		catch(Exception e) {System.out.println("Error in creating new Account row in database"); e.printStackTrace();}

		count++; 
Toolkit.getDefaultToolkit().beep();                
JOptionPane.showMessageDialog(Students.this,
    "New Flight Lesson booked!",
    "Open Account", JOptionPane.PLAIN_MESSAGE);
    // TODO add your handling code here:
    }//GEN-LAST:event_OpenActionPerformed

    private void PreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreviousActionPerformed
                    if(current != 1)
			moveToRow(current-1);    // TODO add your handling code here:
    }//GEN-LAST:event_PreviousActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
                
                cName.setText(" ");
		aNum.setText(" ");
		F_Date.setText(" ");
                cFee.setText(" ");
                cLocation.setText(" ");
                cFlightDur.setText(" ");
                cTutor.setText(" ");
                
                
                
                
                
                //cPhone.setText("");
                Toolkit.getDefaultToolkit().beep();
                
                // TODO add your handling code here:
    }//GEN-LAST:event_ClearActionPerformed

    private void F_DateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F_DateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_F_DateActionPerformed

    private void ExitScreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitScreenActionPerformed
JOptionPane.showMessageDialog(Students.this,
    "You are about to exit. Confirm?",
    "Exit", JOptionPane.PLAIN_MESSAGE);
    Toolkit.getDefaultToolkit().beep();
    System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_ExitScreenActionPerformed

    private void ManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManualActionPerformed

    String https_url="https://www.google.com/";
    URL url;
    try{
        url=new URL(https_url);
        HttpsURLConnection con = (HttpsURLConnection)url.openConnection();
            
    }catch (MalformedURLException e){
        e.printStackTrace();
    }catch(IOException e){
	e.printStackTrace();			        // TODO add your handling code here:
    }//GEN-LAST:event_ManualActionPerformed
    }
    private void cFeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cFeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cFeeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new KennyAir().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    //Delete Student
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(Students.this,
    "Confirm  Closure",
    "Exit", JOptionPane.PLAIN_MESSAGE);
     Toolkit.getDefaultToolkit().beep();
        
        try	// get name to delete from database, use preparedstmt with wildcard
		{
			//AirCraftId = Air_id.getText();
			
			PreparedStatement pstmt = con.prepareStatement("DELETE FROM Students WHERE AirCraft_Id = ?");
			pstmt.setString(1,AirCraftId);
			pstmt.executeUpdate();

			System.out.println(AirCraftId +" deleted from database");

			count --;
		}
		catch(Exception e) {System.out.println("Error in delete button");}
                cName.setText(" ");
		aNum.setText(" ");
		F_Date.setText(" ");
                cFee.setText(" ");
                cLocation.setText(" ");
                cFlightDur.setText(" ");
                cTutor.setText(" ");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ClearDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearDetailsActionPerformed
        // TODO add your handling code here:
                cName.setText(" ");
		aNum.setText(" ");
		F_Date.setText(" ");
                cFee.setText(" ");
                cLocation.setText(" ");
                cFlightDur.setText(" ");
                cTutor.setText(" ");
    }//GEN-LAST:event_ClearDetailsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Students.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Students.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Students.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Students.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Students().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu About;
    private javax.swing.JLabel AccType;
    private javax.swing.JLabel AccType1;
    private javax.swing.JLabel Account;
    private javax.swing.JLabel Account1;
    private javax.swing.JLabel Balance;
    private javax.swing.JLabel BankLogo;
    private javax.swing.JButton Clear;
    private javax.swing.JMenuItem ClearDetails;
    private javax.swing.JButton Exit;
    private javax.swing.JMenuItem ExitScreen;
    private javax.swing.JTextField F_Date;
    private javax.swing.JMenu File;
    private javax.swing.JMenuItem Manual;
    private javax.swing.JLabel Name;
    private javax.swing.JButton Next;
    private javax.swing.JButton Open;
    private javax.swing.JLabel PhoneNr1;
    private javax.swing.JButton Previous;
    private javax.swing.JTextField aNum;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cFee;
    private javax.swing.JTextField cFlightDur;
    private javax.swing.JTextField cLocation;
    private javax.swing.JTextField cName;
    private javax.swing.JTextField cTutor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
